services:
  openlist:
    restart: always
    volumes:
      - '/etc/atlist:/opt/atlist/data'
    ports:
      - '5244:5244'
      - '5245:5245'
    user: '0:0'
    environment:
      - UMASK=022
      - TZ=Asia/Shanghai
    container_name: atlist
    image: 'at13xe/atlist:latest'
